# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selPdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QWidget
from main import execProg

class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_selectPdf = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:(self.btn_selectPdfClicked()))
        self.btn_selectPdf.setGeometry(QtCore.QRect(90, 270, 151, 51))
        self.btn_selectPdf.setObjectName("btn_selectPdf")
        self.lbl_openFile = QtWidgets.QLabel(self.centralwidget)
        self.lbl_openFile.setGeometry(QtCore.QRect(100, 120, 671, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.lbl_openFile.setFont(font)
        self.lbl_openFile.setObjectName("lbl_openFile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def btn_selectPdfClicked(self):

        #Open File Dialog
        pdfFilePath = QFileDialog.getOpenFileName(self, "Open File", "", "Pdf Files (*.pdf)")
        if pdfFilePath:
            print(pdfFilePath[0])
            execProg(_pdfFilePath=pdfFilePath[0])
            
#
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_selectPdf.setText(_translate("MainWindow", "Open PDF File"))
        self.lbl_openFile.setText(_translate("MainWindow", "Open File:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
